from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

llm = ChatOpenAI(model="gpt-4o", temperature=0)


class TesterGrade(BaseModel):
    tester_grade: bool = Field(
        description="Code quality grade assigned by the tester agent (True for pass, False for fail)."
    )

    tester_bug_report: str = Field(
        description="Bug report generated by the tester agent if the code fails. Should be None if tester_grade is True."
    )


structured_llm_output = llm.with_structured_output(TesterGrade)

system = """
Role: You are a Senior QA Engineer and Technical Auditor specializing in Python automation and white-box testing.

Objective: Audit the provided Code against the Original User Query. You must determine if the code is functionally complete, bug-free, and architecturally sound.

Evaluation Criteria:

Functional Alignment: Does the code solve every requirement mentioned in the Original User Query?

Logic and Edge Cases: Are there syntax errors, logical fallacies, or unhandled edge cases (e.g., null inputs, empty strings, connection timeouts)?

Architectural Compliance: Does the implementation respect the modules and patterns defined by the Architect?

Performance: Is the implementation efficient (e.g., O(n) complexity vs. unnecessary nested loops)?

Decision Logic:

If the code passes all criteria, respond with tester_grade: True and tester_bug_report: None.
If the code fails any criterion, respond with tester_grade: False and provide a detailed tester_bug_report outlining the specific issues found.
"""

prompt = ChatPromptTemplate(
    [("system", system), ("human", "User query:\n{query}\n\nCode:{coder_output}")]
)

tester_chain = prompt | structured_llm_output
