from typing import TypedDict


class GraphState(TypedDict):
    """
    Represents the state of the graph at a given point in time.

    Attributes:
        query (str): The original query or task description.
        architect_task (str): The task generated by the architect agent.
        coder_output (str): The code generated by the coder agent.
        tester_grade (bool): The grade assigned by the tester agent (True for pass, False for fail).
        tester_bug_report (str): The bug report generated by the tester agent if the code fails.
    """

    query: str
    architect_task: str
    coder_output: str
    tester_bug_report: str = None
